apptool:
    resource: "@apptoolBundle/Resources/config/routing.yml"
    prefix:   /

coreuser:
    resource: "@coreuserBundle/Resources/config/routing.yml"
    prefix:   /

coretool:
    resource: "@coretoolBundle/Resources/config/routing.yml"
    prefix:   /

corepost:
    resource: "@corepostBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@mainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
